// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "../ShortcutActionDispatch.idl";

namespace TerminalApp
{
    [default_interface] runtimeclass TabSwitcherControl : Windows.UI.Xaml.Controls.Grid
    {
        TabSwitcherControl();

		void ToggleVisibility();

		void SetDispatch(ShortcutActionDispatch dispatch);

		event Windows.Foundation.TypedEventHandler<TabSwitcherControl, Windows.UI.Xaml.RoutedEventArgs> Closed;
    }
}
