// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace TerminalApp
{
    [default_interface] runtimeclass TabSwitcherControl : Windows.UI.Xaml.Controls.Grid
    {
        TabSwitcherControl();

		void ToggleVisibility();
    }
}
